name: Build and Deploy Code

on: [push, pull_requests]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v2
      - name: say hi to Tarun
        run: echo "Hello Tarun"

